package com.roelias.crud.entities;

import com.fasterxml.jackson.databind.JsonNode;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static com.roelias.crud.CRUD.*;

@Table(value = "complex_entities")
public class TestUserMysql {

    // Auto-generated primary key
    @Id(autoGenerated = true)
    private Long id;

    // Manual ID (for cases where you provide the ID)
    // @Id(autoGenerated = false)
    // private String customId;

    // Basic column mapping
    @Column("entity_name")
    private String name;

    // UUID auto-generation
    @UUID(autoGenerate = true)
    @Column("uuid_field")
    private String uuid;

    // Manual UUID (when you want to provide it)
    @UUID(autoGenerate = false)
    private String manualUuid;

    // JSON serialization - supports Objects, Maps, JsonNode
    @JsonColumn
    @Column("preferences_json")
    private UserPreferences preferences;  // Custom object

    @JsonColumn
    private Map<String, Object> metadata;  // Map

    @JsonColumn
    private JsonNode rawJson;  // JsonNode

    // Array handling
    @ArrayColumn(separator = ",")
    private List<String> tags;

    @ArrayColumn(separator = "|")
    private String[] categories;

    // Enum handling - STRING mode
    @EnumColumn(EnumColumn.EnumType.STRING)
    private Status status;

    // Enum handling - ORDINAL mode
    @EnumColumn(EnumColumn.EnumType.ORDINAL)
    private Priority priority;

    // Enum handling - CODE mode (requires getCode() method)
    @EnumColumn(EnumColumn.EnumType.CODE)
    private Department department;

    // File storage
    @FileColumn
    private byte[] document;

    // Default values
    @Default("true")
    private Boolean active;

    @Default("0")
    private Integer attempts;

    // Automatic timestamps
    @CreatedDate
    private LocalDateTime createdAt;

    @UpdatedDate
    private LocalDateTime updatedAt;

    // Ignored field (not persisted)
    @Ignore
    private String temporaryField;

}
